## NumPy

In [1]:
import numpy as np

In [2]:
v1 = np.array([1,2,3,4,5,6,7,8,9])
v1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
m1 = np.array([ [1,2,3],[4,5,6],[7,8,9] ])
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
v1.shape

(9,)

In [5]:
m1.shape

(3, 3)

In [6]:
v2 = np.array([1,2,3,4,5,6,7,8,9])
v2.shape = (3,3)
v2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
print("elemento centrale:", v2[1,1])

elemento centrale: 5


In [8]:
v2[1,1] = 99
v2

array([[ 1,  2,  3],
       [ 4, 99,  6],
       [ 7,  8,  9]])

In [9]:
n = np.array([1,2,3,4,5,6,7,8,9])
print(n[-1])

9


In [10]:
print(n[3:5])

[4 5]


In [11]:
print(n[3:])
print(n[:5])

[4 5 6 7 8 9]
[1 2 3 4 5]


In [12]:
m1[1]

array([4, 5, 6])

In [13]:
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
m1[:, 0]

array([1, 4, 7])

In [15]:
print( m1[1:3, 1:3] ) 


[[5 6]
 [8 9]]


In [16]:
v1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
l2 = np.append(v1, 100)
print("v1:", v1)
print("l2:", l2)

v1: [1 2 3 4 5 6 7 8 9]
l2: [  1   2   3   4   5   6   7   8   9 100]


In [18]:
l3 = np.insert(v1, 3, 100)
print("v1:", v1)
print("l3:", l3)

v1: [1 2 3 4 5 6 7 8 9]
l3: [  1   2   3 100   4   5   6   7   8   9]


In [19]:
v1.dtype

dtype('int64')

In [20]:
l4 = np.array([1.2, 23.4, 45.6])
l4.dtype

dtype('float64')

In [21]:
print(v1)
v1[2] = 12.34
print(v1)

[1 2 3 4 5 6 7 8 9]
[ 1  2 12  4  5  6  7  8  9]


In [22]:
d1 = np.array( v1, dtype=float )
d1

array([ 1.,  2., 12.,  4.,  5.,  6.,  7.,  8.,  9.])

In [23]:
d1[2] = 12.34
print(d1)

[ 1.    2.   12.34  4.    5.    6.    7.    8.    9.  ]


In [24]:
d1.dtype

dtype('float64')

In [25]:
d1.dtype = np.int16
d1

array([     0,      0,      0,  16368,      0,      0,      0,  16384,
        18350,  31457, -20972,  16424,      0,      0,      0,  16400,
            0,      0,      0,  16404,      0,      0,      0,  16408,
            0,      0,      0,  16412,      0,      0,      0,  16416,
            0,      0,      0,  16418], dtype=int16)

## Operazioni

In [26]:
a = np.array([25,50,75,100])
b = np.array([12,23,34,45])

print(a+b)
print(a-b)
print(a*b)
print(a*0.5)

[ 37  73 109 145]
[13 27 41 55]
[ 300 1150 2550 4500]
[12.5 25.  37.5 50. ]


In [27]:
a > 60

array([False, False,  True,  True])

## Generare array

In [28]:
v = np.arange(1,10)
print(v, v.shape)

[1 2 3 4 5 6 7 8 9] (9,)


In [29]:
v = np.arange(1,10).reshape(3,3)
print(v, v.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [30]:
n1 = np.random.random((4,4))
n1

array([[0.96809356, 0.84577232, 0.88914515, 0.043841  ],
       [0.72793839, 0.74825385, 0.38745714, 0.08923234],
       [0.66811744, 0.58448942, 0.2731344 , 0.44437477],
       [0.52465068, 0.91461053, 0.95468743, 0.16076844]])

In [31]:
n1 * 100.0

array([[96.80935591, 84.57723235, 88.91451489,  4.38409969],
       [72.79383896, 74.82538506, 38.74571391,  8.92323431],
       [66.81174393, 58.44894218, 27.31344046, 44.43747679],
       [52.46506841, 91.46105259, 95.46874339, 16.07684434]])

In [32]:
n2 = np.random.randint(0,100, (4,4))
n2

array([[85, 25, 96, 29],
       [95, 33, 55, 71],
       [ 7, 23, 90, 45],
       [79, 42, 55, 59]])

In [33]:
n3 = np.empty((3,3))
print(n3)

[[4.9e-324 9.9e-324 1.5e-323]
 [2.0e-323 2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323 4.4e-323]]


In [34]:
n4 = np.zeros((4,4))
print(n4)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [35]:
n4 = np.ones((4,4))
print(n4)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [36]:
n4 = np.full((4,4), 5)
print(n4)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


## filtri

In [37]:
n = np.random.randint(0,100, 20)
print(n)

[62  3 66 85 97 93 36 10 82 76 95 96 32 60 92 57 97 46 47  1]


In [38]:
n2 = np.arange(0,50)
print(n2)
np.random.shuffle(n2)
print(n2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
[19 27 44 12 22 40 42 26 29 35 30  6 18 38 45 13  8 21 49 25 34 11 31  1
 33 37 14 32 48 36 23  5 16  9  4 43 15  0 17 20 46 41  2 39 47 10 28 24
  3  7]


In [39]:
print( n2[n2 < 20] )

[19 12  6 18 13  8 11  1 14  5 16  9  4 15  0 17  2 10  3  7]


In [40]:
print( n2[n2 == 10] )

[10]


In [41]:
print( n2[ n2%2 == 0 ] )

[44 12 22 40 42 26 30  6 18 38  8 34 14 32 48 36 16  4  0 20 46  2 10 28
 24]


In [42]:
print( n2[ (n2 > 40) | (n2 < 10) ] )

[44 42  6 45  8 49  1 48  5  9  4 43  0 46 41  2 47  3  7]


In [43]:
print( n2[ (n2 < 30) & (n2 > 20) ] )

[27 22 26 29 21 25 23 28 24]


In [44]:
nn = np.where( (n2%2 == 0), "P", "D" )
print(nn)

['D' 'D' 'P' 'P' 'P' 'P' 'P' 'P' 'D' 'D' 'P' 'P' 'P' 'P' 'D' 'D' 'P' 'D'
 'D' 'D' 'P' 'D' 'D' 'D' 'D' 'D' 'P' 'P' 'P' 'P' 'D' 'D' 'P' 'D' 'P' 'D'
 'D' 'P' 'D' 'P' 'P' 'D' 'P' 'D' 'D' 'P' 'P' 'P' 'D' 'D']


## Files


In [45]:
lista = np.genfromtxt('numeri.txt')
print(lista)

[32.54 78.91 15.03 99.99  4.27 65.82 21.16 87.35 50.    1.79]


In [46]:
lista = lista * 1.20
print(lista)

[ 39.048  94.692  18.036 119.988   5.124  78.984  25.392 104.82   60.
   2.148]


In [47]:
np.savetxt("numeri2.txt", lista, fmt='%0.2f')

In [48]:
lista2 = np.loadtxt('numeri.csv', delimiter=',', skiprows=0)
print(lista2)

[[12.34 98.76]
 [56.78 34.56]
 [78.9  12.34]
 [34.56 98.76]
 [98.76 56.78]
 [12.34 78.9 ]
 [56.78 34.56]
 [78.9  98.76]
 [34.56 12.34]
 [98.76 56.78]
 [12.34 78.9 ]
 [56.78 34.56]
 [78.9  98.76]
 [34.56 12.34]
 [98.76 56.78]
 [12.34 78.9 ]
 [56.78 34.56]
 [78.9  98.76]
 [34.56 12.34]
 [98.76 56.78]]


In [49]:
np.save('dati1', lista2)

In [51]:
data = np.load('dati1.npy')
print(data)

[[12.34 98.76]
 [56.78 34.56]
 [78.9  12.34]
 [34.56 98.76]
 [98.76 56.78]
 [12.34 78.9 ]
 [56.78 34.56]
 [78.9  98.76]
 [34.56 12.34]
 [98.76 56.78]
 [12.34 78.9 ]
 [56.78 34.56]
 [78.9  98.76]
 [34.56 12.34]
 [98.76 56.78]
 [12.34 78.9 ]
 [56.78 34.56]
 [78.9  98.76]
 [34.56 12.34]
 [98.76 56.78]]
